export const ADD_TO_PLAYLIST="ADD_TO_PLAYLIST"
export const REMOVE_FROM_PLAYLIST="REMOVE_FROM_PLAYLIST"
export const EMPTY_PLAYLIST="EMPTY_PLAYLIST"
export const PRODUCT_LIST="PRODUCT_LIST"
export const SET_PRODUCT_LIST="SET_PRODUCT_LIST"
export const SEARCH_PRODUCT="SEARCH_PRODUCT"
export const SEARCH_MOVIES="SEARCH_MOVIES"
export const CATAGORY_MOVIES="CATAGORY_MOVIES"
export const CATAGORY_PRODUCT="CATAGORY_PRODUCT"
export const POPULAR_PRODUCT="POPULAR_PRODUCT"
export const TRENDING_PRODUCT="TRENDING_PRODUCT"
export const TV_LIST="TV_LIST"
export const TOP_LIST="TOP_LIST"
export const UPCOMING_LIST="UPCOMING_LIST"






